export const PERMISSION = {
  PROFILE_READ: 'profile.read',
  PROFILE_UPDATE: 'profile.update',
  ACCOUNT_DELETION_REQUEST: 'account.deletion.request',
  CART_MANAGE: 'cart.manage',
  ORDER_CHECKOUT: 'order.checkout',
  ORDER_READ: 'order.read',
  ORDER_CANCEL: 'order.cancel',
  ORDER_CONFIRM: 'order.confirm',
  ORDER_PREPARE: 'order.prepare',
  ORDER_READY: 'order.ready',
  ORDER_COMPLETE: 'order.complete',
  REVIEW_CREATE: 'review.create',
  REVIEW_UPDATE: 'review.update',
  REVIEW_DELETE: 'review.delete',
  REVIEW_MODERATE: 'review.moderate',
  PLACE_CREATE: 'place.create',
  PLACE_READ: 'place.read',
  PLACE_UPDATE: 'place.update',
  PLACE_PUBLISH: 'place.publish',
  PLACE_DELETE: 'place.delete',
  TABLE_READ: 'table.read',
  TABLE_CREATE: 'table.create',
  TABLE_UPDATE: 'table.update',
  TABLE_DELETE: 'table.delete',
  MENU_CREATE: 'menu.create',
  MENU_UPDATE: 'menu.update',
  MENU_DELETE: 'menu.delete',
  PLACE_MEMBER_READ: 'place_member.read',
  CASHIER_ASSIGN: 'cashier.assign',
  CASHIER_REVOKE: 'cashier.revoke',
  OWNER_ASSIGN: 'owner.assign',
  OWNER_REVOKE: 'owner.revoke',
  PLATFORM_ROLE_ASSIGN: 'platform_role.assign',
  PLATFORM_ROLE_UPDATE: 'platform_role.update',
  USER_READ: 'user.read',
  USER_DEACTIVATE: 'user.deactivate',
  MEDIA_UPLOAD: 'media.upload',
  MEDIA_DELETE: 'media.delete',
} as const;

export type PermissionIdentifier = (typeof PERMISSION)[keyof typeof PERMISSION];
export type EffectivePermissions = PermissionIdentifier[];

export const PERMISSIONS = Object.freeze(Object.values(PERMISSION)) as readonly PermissionIdentifier[];
