/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomerRouteImport } from './routes/_customer'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as CustomerOrdersRouteImport } from './routes/_customer.orders'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardBusinessHoursRouteImport } from './routes/dashboard.business-hours'
import { Route as DashboardDiningTablesRouteImport } from './routes/dashboard.dining-tables'
import { Route as DashboardMembersRouteImport } from './routes/dashboard.members'
import { Route as DashboardMenuRouteImport } from './routes/dashboard.menu'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as CustomerAccountProfileRouteImport } from './routes/_customer.account.profile'
import { Route as CustomerAccountReviewsRouteImport } from './routes/_customer.account.reviews'
import { Route as CustomerOrdersOrderIdRouteImport } from './routes/_customer.orders.$orderId'
import { Route as PublicPlacesSlugRouteImport } from './routes/_public.places.$slug'
import { Route as PublicVerifyTokenRouteImport } from './routes/_public.verify.$token'
import { Route as DashboardAccountOrdersRouteImport } from './routes/dashboard.account.orders'
import { Route as DashboardAccountProfileRouteImport } from './routes/dashboard.account.profile'
import { Route as DashboardAccountReviewsRouteImport } from './routes/dashboard.account.reviews'
import { Route as DashboardPlatformOrdersRouteImport } from './routes/dashboard.platform.orders'
import { Route as DashboardPlatformPlacesRouteImport } from './routes/dashboard.platform.places'
import { Route as DashboardPlatformReviewsRouteImport } from './routes/dashboard.platform.reviews'
import { Route as DashboardPlatformUsersRouteImport } from './routes/dashboard.platform.users'
import { Route as CustomerPlacesSlugCartRouteImport } from './routes/_customer.places.$slug.cart'
import { Route as CustomerPlacesSlugCheckoutRouteImport } from './routes/_customer.places.$slug.checkout'
import { Route as PublicPlacesSlugMenuRouteImport } from './routes/_public.places.$slug.menu'
import { Route as DashboardPlatformPlacesPlaceIdRouteImport } from './routes/dashboard.platform.places_.$placeId'
import { Route as DashboardPlatformPlacesNewRouteImport } from './routes/dashboard.platform.places_.new'

const CustomerRoute = CustomerRouteImport.update({
  id: '/_customer',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrdersRoute = CustomerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => CustomerRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessHoursRoute = DashboardBusinessHoursRouteImport.update({
  id: '/business-hours',
  path: '/business-hours',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDiningTablesRoute = DashboardDiningTablesRouteImport.update({
  id: '/dining-tables',
  path: '/dining-tables',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenuRoute = DashboardMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const CustomerAccountProfileRoute = CustomerAccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerAccountReviewsRoute = CustomerAccountReviewsRouteImport.update({
  id: '/account/reviews',
  path: '/account/reviews',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerOrdersOrderIdRoute = CustomerOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => CustomerOrdersRoute,
} as any)
const PublicPlacesSlugRoute = PublicPlacesSlugRouteImport.update({
  id: '/places/$slug',
  path: '/places/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicVerifyTokenRoute = PublicVerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardAccountOrdersRoute = DashboardAccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountProfileRoute = DashboardAccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountReviewsRoute = DashboardAccountReviewsRouteImport.update({
  id: '/account/reviews',
  path: '/account/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlatformOrdersRoute = DashboardPlatformOrdersRouteImport.update({
  id: '/platform/orders',
  path: '/platform/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlatformPlacesRoute = DashboardPlatformPlacesRouteImport.update({
  id: '/platform/places',
  path: '/platform/places',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlatformReviewsRoute =
  DashboardPlatformReviewsRouteImport.update({
    id: '/platform/reviews',
    path: '/platform/reviews',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPlatformUsersRoute = DashboardPlatformUsersRouteImport.update({
  id: '/platform/users',
  path: '/platform/users',
  getParentRoute: () => DashboardRoute,
} as any)
const CustomerPlacesSlugCartRoute = CustomerPlacesSlugCartRouteImport.update({
  id: '/places/$slug/cart',
  path: '/places/$slug/cart',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerPlacesSlugCheckoutRoute =
  CustomerPlacesSlugCheckoutRouteImport.update({
    id: '/places/$slug/checkout',
    path: '/places/$slug/checkout',
    getParentRoute: () => CustomerRoute,
  } as any)
const PublicPlacesSlugMenuRoute = PublicPlacesSlugMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => PublicPlacesSlugRoute,
} as any)
const DashboardPlatformPlacesPlaceIdRoute =
  DashboardPlatformPlacesPlaceIdRouteImport.update({
    id: '/platform/places_/$placeId',
    path: '/platform/places/$placeId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPlatformPlacesNewRoute =
  DashboardPlatformPlacesNewRouteImport.update({
    id: '/platform/places_/new',
    path: '/platform/places/new',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/register': typeof RegisterRoute
  '/orders': typeof CustomerOrdersRouteWithChildren
  '/dashboard/business-hours': typeof DashboardBusinessHoursRoute
  '/dashboard/dining-tables': typeof DashboardDiningTablesRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/account/profile': typeof CustomerAccountProfileRoute
  '/account/reviews': typeof CustomerAccountReviewsRoute
  '/orders/$orderId': typeof CustomerOrdersOrderIdRoute
  '/places/$slug': typeof PublicPlacesSlugRouteWithChildren
  '/verify/$token': typeof PublicVerifyTokenRoute
  '/dashboard/account/orders': typeof DashboardAccountOrdersRoute
  '/dashboard/account/profile': typeof DashboardAccountProfileRoute
  '/dashboard/account/reviews': typeof DashboardAccountReviewsRoute
  '/dashboard/platform/orders': typeof DashboardPlatformOrdersRoute
  '/dashboard/platform/places': typeof DashboardPlatformPlacesRoute
  '/dashboard/platform/reviews': typeof DashboardPlatformReviewsRoute
  '/dashboard/platform/users': typeof DashboardPlatformUsersRoute
  '/places/$slug/cart': typeof CustomerPlacesSlugCartRoute
  '/places/$slug/checkout': typeof CustomerPlacesSlugCheckoutRoute
  '/places/$slug/menu': typeof PublicPlacesSlugMenuRoute
  '/dashboard/platform/places/$placeId': typeof DashboardPlatformPlacesPlaceIdRoute
  '/dashboard/platform/places/new': typeof DashboardPlatformPlacesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/register': typeof RegisterRoute
  '/orders': typeof CustomerOrdersRouteWithChildren
  '/dashboard/business-hours': typeof DashboardBusinessHoursRoute
  '/dashboard/dining-tables': typeof DashboardDiningTablesRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/account/profile': typeof CustomerAccountProfileRoute
  '/account/reviews': typeof CustomerAccountReviewsRoute
  '/orders/$orderId': typeof CustomerOrdersOrderIdRoute
  '/places/$slug': typeof PublicPlacesSlugRouteWithChildren
  '/verify/$token': typeof PublicVerifyTokenRoute
  '/dashboard/account/orders': typeof DashboardAccountOrdersRoute
  '/dashboard/account/profile': typeof DashboardAccountProfileRoute
  '/dashboard/account/reviews': typeof DashboardAccountReviewsRoute
  '/dashboard/platform/orders': typeof DashboardPlatformOrdersRoute
  '/dashboard/platform/places': typeof DashboardPlatformPlacesRoute
  '/dashboard/platform/reviews': typeof DashboardPlatformReviewsRoute
  '/dashboard/platform/users': typeof DashboardPlatformUsersRoute
  '/places/$slug/cart': typeof CustomerPlacesSlugCartRoute
  '/places/$slug/checkout': typeof CustomerPlacesSlugCheckoutRoute
  '/places/$slug/menu': typeof PublicPlacesSlugMenuRoute
  '/dashboard/platform/places/$placeId': typeof DashboardPlatformPlacesPlaceIdRoute
  '/dashboard/platform/places/new': typeof DashboardPlatformPlacesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_customer': typeof CustomerRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/register': typeof RegisterRoute
  '/_customer/orders': typeof CustomerOrdersRouteWithChildren
  '/dashboard/business-hours': typeof DashboardBusinessHoursRoute
  '/dashboard/dining-tables': typeof DashboardDiningTablesRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/_public/': typeof PublicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_customer/account/profile': typeof CustomerAccountProfileRoute
  '/_customer/account/reviews': typeof CustomerAccountReviewsRoute
  '/_customer/orders/$orderId': typeof CustomerOrdersOrderIdRoute
  '/_public/places/$slug': typeof PublicPlacesSlugRouteWithChildren
  '/_public/verify/$token': typeof PublicVerifyTokenRoute
  '/dashboard/account/orders': typeof DashboardAccountOrdersRoute
  '/dashboard/account/profile': typeof DashboardAccountProfileRoute
  '/dashboard/account/reviews': typeof DashboardAccountReviewsRoute
  '/dashboard/platform/orders': typeof DashboardPlatformOrdersRoute
  '/dashboard/platform/places': typeof DashboardPlatformPlacesRoute
  '/dashboard/platform/reviews': typeof DashboardPlatformReviewsRoute
  '/dashboard/platform/users': typeof DashboardPlatformUsersRoute
  '/_customer/places/$slug/cart': typeof CustomerPlacesSlugCartRoute
  '/_customer/places/$slug/checkout': typeof CustomerPlacesSlugCheckoutRoute
  '/_public/places/$slug/menu': typeof PublicPlacesSlugMenuRoute
  '/dashboard/platform/places_/$placeId': typeof DashboardPlatformPlacesPlaceIdRoute
  '/dashboard/platform/places_/new': typeof DashboardPlatformPlacesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/not-found'
    | '/register'
    | '/orders'
    | '/dashboard/business-hours'
    | '/dashboard/dining-tables'
    | '/dashboard/members'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/account/profile'
    | '/account/reviews'
    | '/orders/$orderId'
    | '/places/$slug'
    | '/verify/$token'
    | '/dashboard/account/orders'
    | '/dashboard/account/profile'
    | '/dashboard/account/reviews'
    | '/dashboard/platform/orders'
    | '/dashboard/platform/places'
    | '/dashboard/platform/reviews'
    | '/dashboard/platform/users'
    | '/places/$slug/cart'
    | '/places/$slug/checkout'
    | '/places/$slug/menu'
    | '/dashboard/platform/places/$placeId'
    | '/dashboard/platform/places/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/not-found'
    | '/register'
    | '/orders'
    | '/dashboard/business-hours'
    | '/dashboard/dining-tables'
    | '/dashboard/members'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/dashboard'
    | '/account/profile'
    | '/account/reviews'
    | '/orders/$orderId'
    | '/places/$slug'
    | '/verify/$token'
    | '/dashboard/account/orders'
    | '/dashboard/account/profile'
    | '/dashboard/account/reviews'
    | '/dashboard/platform/orders'
    | '/dashboard/platform/places'
    | '/dashboard/platform/reviews'
    | '/dashboard/platform/users'
    | '/places/$slug/cart'
    | '/places/$slug/checkout'
    | '/places/$slug/menu'
    | '/dashboard/platform/places/$placeId'
    | '/dashboard/platform/places/new'
  id:
    | '__root__'
    | '/_customer'
    | '/_public'
    | '/dashboard'
    | '/login'
    | '/not-found'
    | '/register'
    | '/_customer/orders'
    | '/dashboard/business-hours'
    | '/dashboard/dining-tables'
    | '/dashboard/members'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/_public/'
    | '/dashboard/'
    | '/_customer/account/profile'
    | '/_customer/account/reviews'
    | '/_customer/orders/$orderId'
    | '/_public/places/$slug'
    | '/_public/verify/$token'
    | '/dashboard/account/orders'
    | '/dashboard/account/profile'
    | '/dashboard/account/reviews'
    | '/dashboard/platform/orders'
    | '/dashboard/platform/places'
    | '/dashboard/platform/reviews'
    | '/dashboard/platform/users'
    | '/_customer/places/$slug/cart'
    | '/_customer/places/$slug/checkout'
    | '/_public/places/$slug/menu'
    | '/dashboard/platform/places_/$placeId'
    | '/dashboard/platform/places_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CustomerRoute: typeof CustomerRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_customer': {
      id: '/_customer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_customer/orders': {
      id: '/_customer/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof CustomerOrdersRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-hours': {
      id: '/dashboard/business-hours'
      path: '/business-hours'
      fullPath: '/dashboard/business-hours'
      preLoaderRoute: typeof DashboardBusinessHoursRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dining-tables': {
      id: '/dashboard/dining-tables'
      path: '/dining-tables'
      fullPath: '/dashboard/dining-tables'
      preLoaderRoute: typeof DashboardDiningTablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/members': {
      id: '/dashboard/members'
      path: '/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/menu': {
      id: '/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof DashboardMenuRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_customer/account/profile': {
      id: '/_customer/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof CustomerAccountProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/account/reviews': {
      id: '/_customer/account/reviews'
      path: '/account/reviews'
      fullPath: '/account/reviews'
      preLoaderRoute: typeof CustomerAccountReviewsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/orders/$orderId': {
      id: '/_customer/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof CustomerOrdersOrderIdRouteImport
      parentRoute: typeof CustomerOrdersRoute
    }
    '/_public/places/$slug': {
      id: '/_public/places/$slug'
      path: '/places/$slug'
      fullPath: '/places/$slug'
      preLoaderRoute: typeof PublicPlacesSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/verify/$token': {
      id: '/_public/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof PublicVerifyTokenRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/account/orders': {
      id: '/dashboard/account/orders'
      path: '/account/orders'
      fullPath: '/dashboard/account/orders'
      preLoaderRoute: typeof DashboardAccountOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account/profile': {
      id: '/dashboard/account/profile'
      path: '/account/profile'
      fullPath: '/dashboard/account/profile'
      preLoaderRoute: typeof DashboardAccountProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account/reviews': {
      id: '/dashboard/account/reviews'
      path: '/account/reviews'
      fullPath: '/dashboard/account/reviews'
      preLoaderRoute: typeof DashboardAccountReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/platform/orders': {
      id: '/dashboard/platform/orders'
      path: '/platform/orders'
      fullPath: '/dashboard/platform/orders'
      preLoaderRoute: typeof DashboardPlatformOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/platform/places': {
      id: '/dashboard/platform/places'
      path: '/platform/places'
      fullPath: '/dashboard/platform/places'
      preLoaderRoute: typeof DashboardPlatformPlacesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/platform/reviews': {
      id: '/dashboard/platform/reviews'
      path: '/platform/reviews'
      fullPath: '/dashboard/platform/reviews'
      preLoaderRoute: typeof DashboardPlatformReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/platform/users': {
      id: '/dashboard/platform/users'
      path: '/platform/users'
      fullPath: '/dashboard/platform/users'
      preLoaderRoute: typeof DashboardPlatformUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_customer/places/$slug/cart': {
      id: '/_customer/places/$slug/cart'
      path: '/places/$slug/cart'
      fullPath: '/places/$slug/cart'
      preLoaderRoute: typeof CustomerPlacesSlugCartRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/places/$slug/checkout': {
      id: '/_customer/places/$slug/checkout'
      path: '/places/$slug/checkout'
      fullPath: '/places/$slug/checkout'
      preLoaderRoute: typeof CustomerPlacesSlugCheckoutRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_public/places/$slug/menu': {
      id: '/_public/places/$slug/menu'
      path: '/menu'
      fullPath: '/places/$slug/menu'
      preLoaderRoute: typeof PublicPlacesSlugMenuRouteImport
      parentRoute: typeof PublicPlacesSlugRoute
    }
    '/dashboard/platform/places_/$placeId': {
      id: '/dashboard/platform/places_/$placeId'
      path: '/platform/places/$placeId'
      fullPath: '/dashboard/platform/places/$placeId'
      preLoaderRoute: typeof DashboardPlatformPlacesPlaceIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/platform/places_/new': {
      id: '/dashboard/platform/places_/new'
      path: '/platform/places/new'
      fullPath: '/dashboard/platform/places/new'
      preLoaderRoute: typeof DashboardPlatformPlacesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface CustomerOrdersRouteChildren {
  CustomerOrdersOrderIdRoute: typeof CustomerOrdersOrderIdRoute
}

const CustomerOrdersRouteChildren: CustomerOrdersRouteChildren = {
  CustomerOrdersOrderIdRoute: CustomerOrdersOrderIdRoute,
}

const CustomerOrdersRouteWithChildren = CustomerOrdersRoute._addFileChildren(
  CustomerOrdersRouteChildren,
)

interface CustomerRouteChildren {
  CustomerOrdersRoute: typeof CustomerOrdersRouteWithChildren
  CustomerAccountProfileRoute: typeof CustomerAccountProfileRoute
  CustomerAccountReviewsRoute: typeof CustomerAccountReviewsRoute
  CustomerPlacesSlugCartRoute: typeof CustomerPlacesSlugCartRoute
  CustomerPlacesSlugCheckoutRoute: typeof CustomerPlacesSlugCheckoutRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerOrdersRoute: CustomerOrdersRouteWithChildren,
  CustomerAccountProfileRoute: CustomerAccountProfileRoute,
  CustomerAccountReviewsRoute: CustomerAccountReviewsRoute,
  CustomerPlacesSlugCartRoute: CustomerPlacesSlugCartRoute,
  CustomerPlacesSlugCheckoutRoute: CustomerPlacesSlugCheckoutRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface PublicPlacesSlugRouteChildren {
  PublicPlacesSlugMenuRoute: typeof PublicPlacesSlugMenuRoute
}

const PublicPlacesSlugRouteChildren: PublicPlacesSlugRouteChildren = {
  PublicPlacesSlugMenuRoute: PublicPlacesSlugMenuRoute,
}

const PublicPlacesSlugRouteWithChildren =
  PublicPlacesSlugRoute._addFileChildren(PublicPlacesSlugRouteChildren)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicPlacesSlugRoute: typeof PublicPlacesSlugRouteWithChildren
  PublicVerifyTokenRoute: typeof PublicVerifyTokenRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicPlacesSlugRoute: PublicPlacesSlugRouteWithChildren,
  PublicVerifyTokenRoute: PublicVerifyTokenRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface DashboardRouteChildren {
  DashboardBusinessHoursRoute: typeof DashboardBusinessHoursRoute
  DashboardDiningTablesRoute: typeof DashboardDiningTablesRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardMenuRoute: typeof DashboardMenuRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountOrdersRoute: typeof DashboardAccountOrdersRoute
  DashboardAccountProfileRoute: typeof DashboardAccountProfileRoute
  DashboardAccountReviewsRoute: typeof DashboardAccountReviewsRoute
  DashboardPlatformOrdersRoute: typeof DashboardPlatformOrdersRoute
  DashboardPlatformPlacesRoute: typeof DashboardPlatformPlacesRoute
  DashboardPlatformReviewsRoute: typeof DashboardPlatformReviewsRoute
  DashboardPlatformUsersRoute: typeof DashboardPlatformUsersRoute
  DashboardPlatformPlacesPlaceIdRoute: typeof DashboardPlatformPlacesPlaceIdRoute
  DashboardPlatformPlacesNewRoute: typeof DashboardPlatformPlacesNewRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBusinessHoursRoute: DashboardBusinessHoursRoute,
  DashboardDiningTablesRoute: DashboardDiningTablesRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardMenuRoute: DashboardMenuRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountOrdersRoute: DashboardAccountOrdersRoute,
  DashboardAccountProfileRoute: DashboardAccountProfileRoute,
  DashboardAccountReviewsRoute: DashboardAccountReviewsRoute,
  DashboardPlatformOrdersRoute: DashboardPlatformOrdersRoute,
  DashboardPlatformPlacesRoute: DashboardPlatformPlacesRoute,
  DashboardPlatformReviewsRoute: DashboardPlatformReviewsRoute,
  DashboardPlatformUsersRoute: DashboardPlatformUsersRoute,
  DashboardPlatformPlacesPlaceIdRoute: DashboardPlatformPlacesPlaceIdRoute,
  DashboardPlatformPlacesNewRoute: DashboardPlatformPlacesNewRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  CustomerRoute: CustomerRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
